import uuid from 'react-native-uuid';

module.exports = [
  {
    id: uuid.v4(),
    name: 'Haunted',
    difficulty: '4',
    players: '2-6',
    time: '60',
    addressLine1: 'Dunda Arcade',
    addressLine2: '5 Linthorpe Mews',
    addressLine3: 'Middlesbrough',
    postCode: 'TS1 1SE',
    phone: '03303203450',
    email: 'Info@Project-Escape.co.uk',
    description:
      'A hospital stands abandoned after some stomach churning rumours of what a doctor did to his young female patient before he fled to avoid the repercussions.\n\n He was never found and brought to justice and her body was never recovered.\n\n Ghost hunters think that means her soul will be trapped there, but you don’t believe that sort of thing, do you?',
    imageURL:
      'https://images.ctfassets.net/aofh5t0xnpi5/1yCkGzGn9BeIrGHIUscYfL/29bef9a39befac81d24e0be3c77a8b09/haunted.webp',
    location: 'Middlesbrough',
    lat: '54.578170',
    lng: '-1.235760',
  },
  {
    id: uuid.v4(),
    name: "Sherlock's Mysterious Manor",
    difficulty: '4',
    players: '2-6',
    time: '60',
    addressLine1: 'Dunda Arcade',
    addressLine2: '5 Linthorpe Mews',
    addressLine3: 'Middlesbrough',
    postCode: 'TS1 1SE',
    phone: '03303203450',
    email: 'Info@Project-Escape.co.uk',
    description:
      'In 1932, Musgrave Manor was rocked by a major incident.. \n\n The butler mysteriously vanished and a priceless family heirloom was thought to be stolen. It was such a harrowing event that the whole family packed up and moved abroad, leaving the manor untouched for years.\n\n That was until Sherlock investigated the case. He now needs your help putting the pieces together.\n\n So get your glad rags on and try solving this unsolvable case.\n\n Can you solve the mysteries of the manor?',
    imageURL:
      'https://images.ctfassets.net/aofh5t0xnpi5/TiQIyUysGEGcqDLhoYSoC/a30dc46529c3ff5ce8de2f0cac9fa32e/Logo.jpg',
    lat: '54.578170',
    lng: '-1.235760',
  },
  {
    id: uuid.v4(),
    name: 'The Empty Cabin',
    difficulty: '3',
    players: '2-6',
    time: '60',
    addressLine1: 'Dundas Arcade',
    addressLine2: '5 Linthorpe Mews',
    addressLine3: 'Middlesbrough',
    postCode: 'TS1 1SE',
    phone: '03303203450',
    email: 'Info@Project-Escape.co.uk',
    description:
      'A cabin stands alone in the woods, nobody seen entering or exiting for a long time.\n\n While out exploring, the heavens open, the thunder crashes, and lightening fills the sky.\n\n You seek shelter in the first place with a roof, a cabin. Luckily, it seems empty.\n\n Can you unravel the secrets of the Empty Cabin?',
    imageURL:
      'https://images.ctfassets.net/aofh5t0xnpi5/2IXcQUepkjgLc8QIkYQIs2/6247d53d3a8ba5b797af8d4aab91c476/empty-cabin.webp',
    lat: '54.578170',
    lng: '-1.235760',
  },
  {
    id: uuid.v4(),
    name: 'Sherlocked: Case of the Hexham Heads',
    difficulty: '3',
    players: '2-6',
    time: '60',
    addressLine1: '7 Hallstile Bank',
    addressLine2: 'Hexham',
    addressLine3: 'Northumberland',
    postCode: 'NE46 3PG',
    phone: '03303203450',
    email: 'Hexham@Project-Escape.co.uk',
    description:
      "Sherlock was investigating the Case of the Hexham Heads, looking into the possibility of the supernatural and mention of Celtic rituals and wolf men. The heads whereabouts have been unknown since 1978.\n\n Can you find clues, solve puzzles, eliminate the impossible and escape Hexham's first escape room in 1 hour?",
    imageURL:
      'https://images.ctfassets.net/aofh5t0xnpi5/4V7UJrkbgCCLxXiL6PExR9/529a0e7e5d265a77a192b293cc941ea3/Sherlock.png',
    lat: '54.97181',
    lng: '-2.100590',
  },
  {
    id: uuid.v4(),
    name: 'The Cursed Attic',
    difficulty: '4',
    players: '2-6',
    time: '60',
    addressLine1: '7 Hallstile Bank',
    addressLine2: 'Hexham, ',
    addressLine3: 'Northumberland',
    postCode: 'NE46 3PG',
    phone: '03303203450',
    email: 'Hexham@Project-Escape.co.uk',
    description:
      "There was no attic on the plans when we moved into our Hexham venue\n\n However, after some of the staff heard bumps in the night, we investigated and found a hidden door that led up some old wooden stairs into an Attic. We talked about redecorating it into one of our themed escape rooms, but we felt an uneasy presence so decided to leave everything where it was.\n\n That is until now when we've decided to open the doors and let the people uncover the attic's secrets for themselves.\n\n Will you Escape the Cursed Attic?",
    imageURL:
      'https://images.ctfassets.net/aofh5t0xnpi5/6C6IviWb7aRfdh9ej8fCVj/fddc4ff877b2e4cdd445e528a1799b34/The_Cursed_Attic_logo.png',
    lat: '54.97181',
    lng: '-2.100590',
  },
];
